
import __ASTRO_IMAGE_IMPORT_Z2bBHaW from "./assets/github-squash-and-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1PusPY from "./assets/gitlab-squash-and-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZF0h56 from "./assets/merge-commit.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Unl51 from "./assets/rebase-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md";
import __ASTRO_IMAGE_IMPORT_c77Op from "./assets/redundant-commits.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zfq7rE from "./assets/rest-architecture.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftypescript-graphql-type-safety%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1xPzsQ from "./assets/squashed-commits.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Zzur9G from "./assets/sublime-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZdJ3eS from "./assets/type-safe-graphql-architecture.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftypescript-graphql-type-safety%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z9O5qT from "./assets/unsafe-graphql-architecture.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftypescript-graphql-type-safety%2Findex.md";
export default new Map([["./assets/github-squash-and-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2bBHaW], ["./assets/gitlab-squash-and-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1PusPY], ["./assets/merge-commit.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md", __ASTRO_IMAGE_IMPORT_ZF0h56], ["./assets/rebase-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md", __ASTRO_IMAGE_IMPORT_Unl51], ["./assets/redundant-commits.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md", __ASTRO_IMAGE_IMPORT_c77Op], ["./assets/rest-architecture.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftypescript-graphql-type-safety%2Findex.md", __ASTRO_IMAGE_IMPORT_Zfq7rE], ["./assets/squashed-commits.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md", __ASTRO_IMAGE_IMPORT_1xPzsQ], ["./assets/sublime-merge.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fclean-git-history%2Findex.md", __ASTRO_IMAGE_IMPORT_Zzur9G], ["./assets/type-safe-graphql-architecture.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftypescript-graphql-type-safety%2Findex.md", __ASTRO_IMAGE_IMPORT_ZdJ3eS], ["./assets/unsafe-graphql-architecture.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Ftypescript-graphql-type-safety%2Findex.md", __ASTRO_IMAGE_IMPORT_Z9O5qT]]);
		