import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import { usePathname } from "next/navigation";
import { Inter } from "next/font/google";
import "./globals.css";
import { fetcher } from "@/utils/fetcher";
import Link from "next/link";
import type { APIResponse } from "@/types/types";
import { SocialButtons } from "@/components/SocialButtons";
import { Navbar } from "./Navbar";
import { Footer } from "./Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const global = (await fetcher("/api/global", {
    populate: [
      "navbarSocialNetworks",
      "footerSocialNetworks",
      "footerSections",
      "footerSections.links",
    ],
  })) as APIResponse<"api::global.global">;

  return (
    <html lang="en">
      <SpeedInsights />
      <Analytics />
      <body
        style={inter.style}
        className="flex flex-col min-h-screen text-gray-800 dark:text-gray-100 "
      >
        {/* Top section */}
        <div className="flex-1 flex flex-col dark:bg-gray-900">
          <Navbar global={global} />
          <main className="flex-1 bg-white dark:bg-gray-900">{children}</main>
        </div>
        <Footer global={global} />
      </body>
    </html>
  );
}
